In [76]:
# SURAJ VERMA 
# AI LAB. 
# BAYESIAN CLASSIFICATION & DECISION TREES ON CHESS DATASET
# necessary comments have been included. 

In [28]:
# importing the libraries - numpy, pandas, matplotlib, sklearn.
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier

In [29]:
# importing the data from the dataset
data = pd.read_csv('games.csv')

In [30]:
data.info() # a basic info about the data set. 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20058 entries, 0 to 20057
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   id              20058 non-null  object 
 1   rated           20058 non-null  bool   
 2   created_at      20058 non-null  float64
 3   last_move_at    20058 non-null  float64
 4   turns           20058 non-null  int64  
 5   victory_status  20058 non-null  object 
 6   winner          20058 non-null  object 
 7   increment_code  20058 non-null  object 
 8   white_id        20058 non-null  object 
 9   white_rating    20058 non-null  int64  
 10  black_id        20058 non-null  object 
 11  black_rating    20058 non-null  int64  
 12  moves           20058 non-null  object 
 13  opening_eco     20058 non-null  object 
 14  opening_name    20058 non-null  object 
 15  opening_ply     20058 non-null  int64  
dtypes: bool(1), float64(2), int64(4), object(9)
memory usage: 2.3+ MB


In [31]:
data.head(10)

id  rated    created_at  last_move_at  turns victory_status winner  \
0  TZJHLljE  False  1.504210e+12  1.504210e+12     13      outoftime  white   
1  l1NXvwaE   True  1.504130e+12  1.504130e+12     16         resign  black   
2  mIICvQHh   True  1.504130e+12  1.504130e+12     61           mate  white   
3  kWKvrqYL   True  1.504110e+12  1.504110e+12     61           mate  white   
4  9tXo1AUZ   True  1.504030e+12  1.504030e+12     95           mate  white   
5  MsoDV9wj  False  1.504240e+12  1.504240e+12      5           draw   draw   
6  qwU9rasv   True  1.504230e+12  1.504230e+12     33         resign  white   
7  RVN0N3VK  False  1.503680e+12  1.503680e+12      9         resign  black   
8  dwF3DJHO   True  1.503510e+12  1.503510e+12     66         resign  black   
9  afoMwnLg   True  1.503440e+12  1.503440e+12    119           mate  white   

  increment_code            white_id  white_rating            black_id  \
0           15+2            bourgris          1500                a-00   
1           5+10                a-00          1322           skinnerua   
2           5+10              ischia          1496                a-00   
3           20+0       daniamurashov          1439        adivanov2009   
4           30+3           nik221107          1523        adivanov2009   
5           10+0           trelynn17          1250       franklin14532   
6           10+0             capa_jr          1520  daniel_likes_chess   
7          15+30  daniel_likes_chess          1413            soultego   
8           15+0           ehabfanri          1439  daniel_likes_chess   
9           10+0  daniel_likes_chess          1381             mirco25   

   black_rating                                              moves  \
0          1191  d4 d5 c4 c6 cxd5 e6 dxe6 fxe6 Nf3 Bb4+ Nc3 Ba5...   
1          1261  d4 Nc6 e4 e5 f4 f6 dxe5 fxe5 fxe5 Nxe5 Qd4 Nc6...   
2          1500  e4 e5 d3 d6 Be3 c6 Be2 b5 Nd2 a5 a4 c5 axb5 Nc...   
3          1454  d4 d5 Nf3 Bf5 Nc3 Nf6 Bf4 Ng4 e3 Nc6 Be2 Qd7 O...   
4          1469  e4 e5 Nf3 d6 d4 Nc6 d5 Nb4 a3 Na6 Nc3 Be7 b4 N...   
5          1002                                   e4 c5 Nf3 Qa5 a3   
6          1423  d4 d5 e4 dxe4 Nc3 Nf6 f3 exf3 Nxf3 Nc6 Bb5 a6 ...   
7          2108                     e4 Nc6 d4 e5 d5 Nce7 c3 Ng6 b4   
8          1392  e4 e5 Bc4 Nc6 Nf3 Nd4 d3 Nxf3+ Qxf3 Nf6 h3 Bc5...   
9          1209  e4 d5 exd5 Qxd5 Nc3 Qe5+ Be2 Na6 d4 Qf5 Bxa6 b...   

  opening_eco                                       opening_name  opening_ply  
0         D10                   Slav Defense: Exchange Variation            5  
1         B00             Nimzowitsch Defense: Kennedy Variation            4  
2         C20              King's Pawn Game: Leonardis Variation            3  
3         D02             Queen's Pawn Game: Zukertort Variation            3  
4         C41                                   Philidor Defense            5  
5         B27               Sicilian Defense: Mongoose Variation            4  
6         D00         Blackmar-Diemer Gambit: Pietrowsky Defense           10  
7         B00  Nimzowitsch Defense: Kennedy Variation |  Link...            5  
8         C50              Italian Game: Schilling-Kostic Gambit            6  
9         B01      Scandinavian Defense: Mieses-Kotroc Variation            4

In [32]:
# let's perform some data cleaning

In [33]:
# deleting unnecessary columns from the dataset 
data.drop('id', axis = 1, inplace=True) # deleting id column
data.drop('created_at', axis = 1, inplace=True) # deleting created_at column
data.drop('last_move_at', axis = 1, inplace=True) # deleting lasy_move_at column
data.drop('increment_code', axis = 1, inplace=True) # deleting increment_code column
data.drop('moves', axis = 1, inplace=True) # deleting moves column
data.drop('opening_eco', axis = 1, inplace=True) # deleting opening_eco col. 
data.drop('opening_name', axis = 1, inplace=True) # deleting opening_name col. 

In [34]:
data.head(5)

rated  turns victory_status winner       white_id  white_rating  \
0  False     13      outoftime  white       bourgris          1500   
1   True     16         resign  black           a-00          1322   
2   True     61           mate  white         ischia          1496   
3   True     61           mate  white  daniamurashov          1439   
4   True     95           mate  white      nik221107          1523   

       black_id  black_rating  opening_ply  
0          a-00          1191            5  
1     skinnerua          1261            4  
2          a-00          1500            3  
3  adivanov2009          1454            3  
4  adivanov2009          1469            5

In [35]:
data.shape # getting an overview of the total rows & cols. after cleaning. 

(20058, 9)

In [36]:
# getting an overview of how many players of both whites & black are good players (>=1200 rating)
data[ (data['white_rating']>=1200) & (data['black_rating']>=1200)]

rated  turns victory_status winner       white_id  white_rating  \
1       True     16         resign  black           a-00          1322   
2       True     61           mate  white         ischia          1496   
3       True     61           mate  white  daniamurashov          1439   
4       True     95           mate  white      nik221107          1523   
6       True     33         resign  white        capa_jr          1520   
...      ...    ...            ...    ...            ...           ...   
20052   True     37         resign  white       jamboger          1219   
20053   True     24         resign  white        belcolt          1691   
20055   True     35           mate  white       jamboger          1219   
20056   True    109         resign  white   marcodisogno          1360   
20057   True     78           mate  black       jamboger          1235   

                 black_id  black_rating  opening_ply  
1               skinnerua          1261            4  
2                    a-00          1500            3  
3            adivanov2009          1454            3  
4            adivanov2009          1469            5  
6      daniel_likes_chess          1423           10  
...                   ...           ...          ...  
20052            samael88          1250            4  
20053            jamboger          1220            2  
20055        schaaksmurf3          1286            3  
20056            jamboger          1227            4  
20057               ffbob          1339            3  

[17400 rows x 9 columns]

### Bayesian classification 

In [37]:
# TIME TO USE BAYESIAN CLASSIFICATION & DECISION TREE

In [45]:
# we use bayesian classification to determine relation between winner and the victory status. 

# using labelencoder()

labelencoder = LabelEncoder()
data['rated'] = labelencoder.fit_transform(data['rated'])
data['turns'] = labelencoder.fit_transform(data['turns'])
data['victory_status'] = labelencoder.fit_transform(data['victory_status'])
data['winner'] = labelencoder.fit_transform(data['winner'])
data['white_rating'] = labelencoder.fit_transform(data['white_rating'])
data['black_rating'] = labelencoder.fit_transform(data['black_rating'])

In [52]:
# printing data we would be using specifically
x = data['winner']
y = data['victory_status']

print(x)
print(y)


0        2
1        0
2        2
3        2
4        2
        ..
20053    2
20054    0
20055    2
20056    2
20057    0
Name: winner, Length: 20058, dtype: int64
0        2
1        3
2        1
3        1
4        1
        ..
20053    3
20054    1
20055    1
20056    3
20057    1
Name: victory_status, Length: 20058, dtype: int64


In [59]:
# splitting data into test/train set

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 0)
print(X_train)
print(y_train)
print(X_test)
print(y_test)

X_train = X_train.values.reshape(-1,1) # series object has no reshape, hence add .values as well. 
y_train = y_train.values.reshape(-1,1)

17567    0
2705     0
13043    2
9890     0
8317     0
        ..
13123    0
19648    0
9845     2
10799    0
2732     0
Name: winner, Length: 14040, dtype: int64
17567    1
2705     3
13043    3
9890     3
8317     2
        ..
13123    3
19648    2
9845     1
10799    3
2732     3
Name: victory_status, Length: 14040, dtype: int64
9870     2
14355    2
10069    0
5951     0
9130     1
        ..
17933    2
19497    0
8542     2
6973     2
15550    2
Name: winner, Length: 6018, dtype: int64
9870     1
14355    3
10069    2
5951     3
9130     2
        ..
17933    1
19497    1
8542     1
6973     1
15550    2
Name: victory_status, Length: 6018, dtype: int64


In [58]:
# training the model on the training set & using naive bayes classifier 
classifier = GaussianNB()
classifier.fit(X_train, y_train)


C:\Users\Surajv\anaconda3\envs\tensorflow\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


GaussianNB()

In [61]:
# predicting the results 
X_test = X_test.values.reshape(-1,1)
y_pred = classifier.predict(X_test)
y_pred

array([3, 3, 3, ..., 3, 3, 3], dtype=int64)

In [62]:
# confusion matrix and accuracy 
confusion_matrix(y_test, y_pred)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.97      1.00      0.98       260
           1       0.00      0.00      0.00      1907
           2       0.00      0.00      0.00       481
           3       0.59      1.00      0.74      3370

    accuracy                           0.60      6018
   macro avg       0.39      0.50      0.43      6018
weighted avg       0.37      0.60      0.46      6018



C:\Users\Surajv\anaconda3\envs\tensorflow\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Decision trees

In [63]:
 # NOW TIME FOR USING DECISION TREES. 

In [64]:
# DECISION TREE CLASSIFIER 
model1 = DecisionTreeClassifier(random_state=1)
model1.fit(X_train, y_train)


DecisionTreeClassifier(random_state=1)

In [65]:
# time to predict 

y_pred1 = model1.predict(X_test)
y_pred1

array([3, 3, 3, ..., 3, 3, 3], dtype=int64)

In [66]:
# confusion matrix and accuracy 

confusion_matrix(y_test,y_pred1)
print(classification_report(y_test, y_pred1))

              precision    recall  f1-score   support

           0       0.97      1.00      0.98       260
           1       0.00      0.00      0.00      1907
           2       0.00      0.00      0.00       481
           3       0.59      1.00      0.74      3370

    accuracy                           0.60      6018
   macro avg       0.39      0.50      0.43      6018
weighted avg       0.37      0.60      0.46      6018



C:\Users\Surajv\anaconda3\envs\tensorflow\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [69]:
# using gini classifier 
clf_gini = DecisionTreeClassifier(criterion = "gini",random_state = 100,max_depth=3, min_samples_leaf=5)

# training using gini 
clf_gini = clf_gini.fit(X_train, y_train)

def prediction(X_test, clf_object):
    y_pred = clf_object.predict(X_test)
    print("predicted values got from gini index:")
    print(y_pred)
    return y_pred

#predicting using gini
y_pred_gini = prediction(X_test, clf_gini)

predicted values got from gini index:
[3 3 3 ... 3 3 3]


In [70]:

# printing the confusion matrix
print(confusion_matrix(y_test, y_pred))

[[ 260    0    0    0]
 [   0    0    0 1907]
 [   8    0    0  473]
 [   0    0    0 3370]]


In [73]:
# accuracy 
print (accuracy_score(y_test,y_pred)*100)

60.31904287138584


In [74]:
# final report       
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.97      1.00      0.98       260
           1       0.00      0.00      0.00      1907
           2       0.00      0.00      0.00       481
           3       0.59      1.00      0.74      3370

    accuracy                           0.60      6018
   macro avg       0.39      0.50      0.43      6018
weighted avg       0.37      0.60      0.46      6018

